### ISSUE TITLE
Setup of stress testing task

### ISSUE THREAD

**Issue by vbkristof** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#43]
# Requirements
You should make a research about possible stress test solutions suited for our application. In order to fulfill this task, please take a look at the current project, which technologies are used, what is the basic architecture etc....

Please make a small **summary**, about what are the **basic principles of stress testing,** and what is neccessary for us to implement. After that please create all neccessary **tickets** for the steps we need to make to fulfill this task.

In addition to that please create a documentation **markdown file** in the docs folder. This file will contain our documentation for this task for the IET homework.

You should also think about the following things:
- Do we need separate test cases for FE and BE?
- What frameworks can we use to have a solid set of stress tests?

# Solution
Please make a research about this task and create all neccessary tickets, in addition to that please document your work here as a comment.

# Acceptance criteria
- The tickets describing all separate tasks should exist.
- The markdown file should exist
- The comments here in the ticket about your work should exist

# Deadline
Please complete this task until 2023.05.13. in order to have enough time to complete the other tasks.

**Comment by benhorv** [comment]
### What is stress testing?

Stress testing is a way to measure real-world performance of our web application. With stress testing we can measure performance, robustness and scalability. Our measures are response time, throughput and concurrent user capacity.

#### How to do stress testing?

- Set our goals. How should our application perform? How many users do we want to serve at a time? How fast should they get their information?
- Identify test scenarios. How can we simulate high loads? When would that happen? Which part of our software would be utilized the most in that case?
- Create tests and scripts based on the scenarios. (On which platform, using what kind of framework?)
- Do the test. (Should we use CI?)
- Evaluate the results.
- Optimize. (Then retest.)
- Document the results.

#### Tool Research

1. Looking up possible tools for stress testing a web application.
    1. [Apache JMeter](https://jmeter.apache.org/): A possible solution, it's free and open source, it can simulate load on servers, services and objects... (anything that uses requests), using multiple protocols (HTTP is the one that's useful for us).
    2. There is a similar tool for GitHub Actions: https://thenewstack.io/simple-load-testing-with-github-actions/
    3. [The Grinder](https://grinder.sourceforge.net/): Also open source and Java-based, not very commonly used, but a bit more modern and simple. Maybe only for Java code?
2. Deciding on a tool: I think JMeter would be the most suitable for us, because of it's popularity, simplicity and robustness.
    1. We can use it for simulating large loads separately on FE, BA, and on the data base.
    2. It also supports CI.
3. Creating tickets:
    1. Set goals of stress testing and identify test scenarios. #53 
    2. Set up JMeter
    3. Create test cases using JMeter. #54 
    4. (Optional) Look for CI options for stress testing. #56
    5. Evaluate stress test results and document them. #55

**Comment by hbede** [comment]
everything done, PR requested

**Comment by benhorv** [comment]
everything done, PR requested
