### ISSUE TITLE
Setup of BDD testing task

### ISSUE THREAD

**Issue by vbkristof** [Hollo-Event-Notifier/Hollo-Event-Notifier-App#44]
# Requirements
You should **make a research about possible BDD test solutions** suited for our application. In order to fulfill this task, please take a look at the current project, which technologies are used, what is the basic architecture etc....

Please make a **small summary**, about what are the basic principles of BDD testing, and what is neccessary for us to implement. After that please create all **neccessary tickets** for the steps we need to make to fulfill this task.

In addition to that please create a documentation **markdown file i**n the docs folder. This file will contain our documentation for this task for the IET homework.

You should also think about the following things:
- Which frameworks can we use to have a solid set of stress tests?
- How should we organize our test cases?

# Solution
Please make a research about this task and create all neccessary tickets, in addition to that please document your work here as a comment.

# Acceptance criteria
- The tickets describing all separate tasks should exist.
- The markdown file should exist
- The comments here in the ticket about your work should exist

# Deadline
Please complete this task until 2023.05.13. in order to have enough time to complete the other tasks.

**Comment by PeterH001** [comment]
# BDD research

Behaviour Driven Development (BDD) is a synthesis and refinement of practices stemming from Test Driven Development (TDD) and Acceptance Test Driven Development (ATDD)

<i>BDD is a process designed to aid the management and the delivery of software development projects by improving communication between engineers and business professionals. In so doing, BDD ensures all development projects remain focused on delivering what the business actually needs while meeting all requirements of the user. </i>

During a project there can be misunderstandings between different groups:
- the business being truly able to define the desired outcomes;
- the developer’s understanding of what needs to be built; and
- the business’ understanding of the technical challenges its requirements may present.

## Properties of BDD

- Set goals ([SMART goals](https://en.wikipedia.org/wiki/SMART_criteria))
- Impact mapping
  - alternative ways to reach your decided goal by analysing users’ behaviour
- Value and complexity analysis (Cynefin)
   -  low-cost, high-value features in the backlog
- Planning in examples
  - describe the most complex of ideas to somebody with a different skills-set without introducing misunderstanding
  - understanding through examples
- ...

More at <https://inviqa.com/blog/bdd-guide>

## Testing frameworks

Most of the frameworks use Gherkin, wich is a business-readable programming language, which describes business behavior without going into detail of how it is implemented.

Gherkin is broken down into a Given-When-Then language construct: 

- Given: Context, such as signing up for a free trial. 
- When: An action that happens due to the previously given context, such as filling out a ‘Free Trial’ form. 
- Then: The outcome, such as a prompt to set up a ‘Trial’ account.   

### [Cucumber](https://cucumber.io/)
-  one of the most popular BDD testing frameworks on the market
-  various languages

### [Quantum](https://help.perfecto.io/perfecto-help/content/perfecto/automation-testing/quantum_framework_introduction.htm)
- for java

### JBehave
- leading BDD framework for Java and other JVM languages, such as Groovy, Kotlin, and Scala
- JBehave does not offer some common Gherkin features

I recommend using Cucumber, we used it 2 years ago and it seems to be the most popular and versatile solution.
- works with:
  - kotlin
  - javascript
    - to make it work with typescript codes, consider these websites:
      - [cucumber7-ts-starter](https://github.com/hdorgeval/cucumber7-ts-starter)
      - [Cucumber.js with TypeScript](https://www.elliotdenolf.com/blog/cucumberjs-with-typescript)

## Creating tickets

- More research in the field of how to make Cucumber work with TS
- [optional] [Getting introduced to Cucumber with JS](https://school.cucumber.io/courses/bdd-with-cucumber-javascript) video course
- Set up Cucumber test framework for the project
- Define examples
- Create BDD tests based on the examples
- Evaluate tests
- Modify application if needed according to test results
